# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7e79a041e4927ff01c766109a8b91d35b8131636017637aeeba709515c33deb17198937b545c3700e94034ed8e829fbb4f5711cfcbad137ea2b5e06db201b81a

test:
  secret_key_base: 97be87a9f9db0afd2f04497d7ce21bcfecf63c19782977f81826f0654053e8b494649c3093a681be86a1cef8ee0d9615ef83411840a3380ecc14e30aaa841c18

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
